DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users(
  id INT NOT NULL PRIMARY KEY,
  username TEXT NOT NULL,
  firstName TEXT DEFAULT NULL,
  lastName TEXT DEFAULT NULL,
  imageUrl TEXT DEFAULT NULL,
  rating INT DEFAULT 2000,
  active BOOLEAN DEFAULT FALSE
);

DROP TABLE IF EXISTS matches;
CREATE TABLE IF NOT EXISTS matches(
  id SERIAL PRIMARY KEY,
  winner INT NOT NULL,
  loser INT NOT NULL,
  winnerScore INT NOT NULL,
  loserScore INT NOT NULL,
  ratingChange INT NOT NULL,
  "time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (winner) REFERENCES users(id),
  FOREIGN KEY (loser) REFERENCES users(id)
);
